repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes", "--skip", "AUTHORS"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.13"
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix", "--unsafe-fixes", "--exit-non-zero-on-fix"]
