name: Checking Code Structure and Running Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python using the default project version
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make devenv

    - name: Check linting and formatting
      run: |
        make checkformat

    - name: Test with tox
      run: |
        pip install pytest
        cd ${GITHUB_WORKSPACE} && python quicktest.py
      env:
        DJANGO_SETTINGS_MODULE: helpdesk.settings

