name: Checking Code Structure and Running Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', 'pypy-3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key:
          ${{ matrix.python-version }}-v1-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ matrix.python-version }}-v1-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make develop

    - name: Check linting and formatting
      run: |
        make checkformat

    - name: Tox tests
      run: |
        tox --verbose

    - name: Upload code coverage for ref branch
      uses: actions/upload-artifact@v3
      with:
        name: ref-lcov.info
        path: ./coverage/lcov.info
